server.port=9090
spring.application.name=diameter-simulator
diameter.simulator.port=3868

logging.level.root=INFO
logging.level.com.telecom.simulator=DEBUG
logging.level.io.netty=WARN
logging.pattern.console=%d{yyyy-MM-dd HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n
